markdown: kramdown
kramdown:
    input: GFM

safe: true
lsi: false

exclude:
  - "bin"
  - "vendor"

sass:
  style: compressed

gems:
  - jekyll-assets

url: "http://toni.uebernickel.info"
baseurl: ""

title: havvg's playground
description: Developing Software is Fun!

favicon: https://secure.gravatar.com/avatar/1b0644b408ccd789b0178b2b0c860cea?s=240
logo: https://secure.gravatar.com/avatar/1b0644b408ccd789b0178b2b0c860cea?s=240

author:
  name: Toni Uebernickel
  email: tuebernickel@gmail.com
  image: https://secure.gravatar.com/avatar/1b0644b408ccd789b0178b2b0c860cea?s=240
  bio: Software Engineer and Architect, Symfony evangelist with some Ducati bikes.
  social:
    - icon: github
      url: https://github.com/havvg
      desc: Fork me on github

    - icon: twitter
      url: https://twitter.com/havvg
      desc: Follow me on twitter

    - icon: linkedin
      url: https://www.linkedin.com/in/havvg
      desc: Connect on LinkedIn

    - icon: xing
      url: https://www.xing.com/profile/Toni_Uebernickel
      desc: Connect on XING

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      comments: false

disqus:
  config:
    - label: disqus_shortname
      value: 'havvgsplayground'

googleanalytics:
  account: UA-738346-7

gosquared:
  account: GSN-841923-G
